spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/DevPubBlogEngine?serverTimezone=Europe/Moscow
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true