blog-engine:
  host:
    baseUrl: http://localhost:8080/

  transaction-repeating:
    max-attempts: 50
    min-delay: 50
    max-delay: 200

  captcha:
    lifetime: 60

  frontend:
    title: DevPub
    subtitle: Рассказы разработчиков
    contact-phone: +7 903 666-44-55
    contact-email: mail@mail.ru
    copyright: Дмитрий Сергеев
    copyright-from: 2005

  upload:
    directory: upload/

  global-settings:
    definitions:
      MULTIUSER_MODE:
        default-value: "NO"
        default-name:

      POST_PREMODERATION:
        default-value: "YES"
        default-name:

      STATISTICS_IS_PUBLIC:
        default-value: "YES"
        default-name:

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/DevPubBlogEngine?serverTimezone=Europe/Moscow
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true