blog-engine:
  host: http://localhost:8080/

  transaction-repeating:
    max-attempts: 50
    min-delay: 50
    max-delay: 200

  frontend-title: DevPub
  frontend-subtitle: Рассказы разработчиков
  contact-phone: +7 903 666-44-55
  contact-email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyright-from: 2005

spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/DevPubBlogEngine?serverTimezone=Europe/Moscow
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true